### PR TITLE
Simplify logic for size changing in partition_on

### PR DESCRIPTION
**Pull request by fjetter**

### CODE REVIEW

**Comment by fjetter** [comment]
@lr4d tests are running through fine. Do you remember what the issue was you were facing?

**Comment by lr4d** [comment]
oops. didn't see that you opened this before force-pushing

I don't remember it off the top of my head, no, some test failure in `io_components` I think

**Comment by fjetter** [comment]
Tests seem to run through with this implementation. I'd prefer this approach since it introduces much less complexity

**Comment by lr4d** [comment]
Sure, thanks

**Pull request merged**
